Abdulsite/urls.py
from django.contrib import admin
from django.urls import path, include


app_name = 'blog'


urlpatterns = [
    path('admin/', admin.site.urls),
   
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/urls.py
from django.urls import path

from . import views 

app_name = 'blog'

urlpatterns = [
# post views
#path('', views.post_list, name='post_list'),
    path('', views.post_list, name= 'post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail,
         name='post_detail'),
     path('<int:post_id>/share/',
          views.post_share, name='post_share'),
     path('<int:post_id>/comment/',
          views.post_comment, name='post_comment'),
]

blog/models.py
from django.db import models

# Create from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
                      .filter(status=Post.Status.PUBLISHED)


class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF' , 'Draft'
        PUBLISHED = 'PB', 'Published'
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')  
    author = models.ForeignKey(User,
                                on_delete=models.CASCADE,
                                related_name='blog_posts')
    body =  models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add= True)
    updated = models.DateTimeField(auto_now = True)
    status = models.CharField(max_length=2,
                             choices=Status.choices,
                             default=Status.DRAFT)
    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]
    
    def __str__(self):
        return self.title 

        


   

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                            args=[self.publish.year,
                                  self.publish.month,
                                  self.publish.day,
                                  self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]
    
def __str__(self):
    return f'Comment by {self.name} on {self.post}'

blog/forms.py
from django import forms
from. models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage,\
                                  PageNotAnInteger
from django.views.generic import ListView 

from .forms import EmailPostForm, CommentForm

from django.core.mail import send_mail

from django.views.decorators.http import require_POST


def post_share(request, post_id):
    #Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False
    
    if request.method == 'POST':
        #Form was submitted
        form  = EmailPostForm(request.POST)
        if form.is_valid():
            #Form fields passed validation
            cd = form.cleaned_data
             #... send email
            post_url = request.build_absolute_uri(
                post.get_absolute_url())
            subject = f"{cd['name']} recommends you read" \
                      f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                       f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'zubedanrdn@gmail.com',
                      [cd['to']])
            sent = True
                                
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html',{'post': post,
                                                   'form': form,
                                                   'sent': sent})
class PostListView(ListView):
    """ 
    Alternative post list view

    """ 
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 2
    template_name = 'blog/post/list.html'
    
def post_list(request):
    post_list = Post.published.all()
          #pagination with 3 posts per page
    paginator = Paginator(post_list, 2)
    page_number = request.GET.get('page', 1) 
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        #if page_number is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        #if page_number is out of range deliver last page of results
        posts = Paginator.page(paginator.num_pages)

    return render(request,
              'blog/post/list.html',
              {'posts': posts})

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post,
                             status=Post.Status.PUBLISHED,
                             slug=post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    
    #list of active comments for this post
    comments = post.comments.filter(active=True)
    #Form for users to comment
    form = CommentForm()
    
    return render(request,
                 'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'form': form})

@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    # A comment was posted
    form = CommentForm(data=request.POST)
    if form.is_valid():
        #create a comment object without saving it to the database
        comment = form.save(commit=False)
        #Assign the post to the comment
        comment.post = post
        #save the comment to the database
        comment.save()
    return render(request, 'blog/post/comment.html',
                           {'post': post,
                            'form': form,
                            'comment': comment})

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static 'blog/css/blog.css' %}" rel="stylesheet">
        
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" >
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" ></script>
        
        </head>
        <body>

                <!-- Correctly written div with inline style for background image -->
        <div class="backgroundimage" style="background-image: url('/static/blog/images/IMG_1701.jpg'); background-size: cover; background-position: center; background-repeat: no-repeat;">
         

          
           
                {% block content %}
                {% endblock %}
             
                <div id="sidebar">
                    <h2>My zuuh</h2>
                    <p> This is my blog</p>
                </div>
 <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
        </body>
</html>
    </div>





                 

blog/templates/blog/post/comment.html
{% extends "blog/base.html" %}

{% block title %}Add a comment{% endblock%}

{% block content%}
  {% if comment %}
    <h2>Your comment has been added.</h2>
    <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
   {% else %}
     {% include "blog/post/includes/comment_form.html" %}

   {% endif %}
{% endblock %}                 

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}{{post.title}}{% endblock %}

{% block content %}
<h1>{{post.title }}</h1>
<p class="date">
    Published {{ post.publish }} by {{ post.author}}
</p>
{{post.body| linebreaks }}
<p>
    <a href="{% url 'blog:post_share' post.id %}">
        Share this post
    </a>
</p>
{% with comments.count as total_comments %}
  <h2>
    {{ total_comments }} comment{{ total_comments|pluralize }}
  </h2>
  {% endwith %}
  {% for comment in comments %}
    <div class="comment">
        <p class="info">
            Comment {{ forloop.counter }} by {{ comment.name }}
            {{ comment.created }}
        </p>
        {{ comment.body|linebreaks }}
    </div>
   {% empty %}
      <p>There are no comments.</p>
    {% endfor %}
    {% include "blog/post/includes/comment_form.html" %}
{% endblock %}

blog/templates/blog/post/includes/comment_form.html
<h2>Add a new comment</h2>
<form action="{% url "blog:post_comment" post.id %}" method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Add comment"></p>
</form>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}My zuuh{% endblock %}

{% block content %}
<h1>My zuuh</h1>
{% for post in posts %}
<h2>
  <a href="{{ post.get_absolute_url }}">
{{ post.title }}
</a>
</h2>
<p class="date">
Published {{ post.publish }} by {{ post.author }}
</p>

   {{ post.body|truncatewords:30|linebreaks }}  
 {% endfor %} 
 {% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{%block title %}Share a post{% endblock %}

{% block content %}
  {% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>
        "{{post.title}}" was successfully sent to {{form.cleaned_data.to }}
    </p>
    {% else %}
      <h1>Share"{{ post.title }}" by e-mail </h1>
      <form method="post">
        {{ form.as_P }}
        {% csrf_token %}
       
        {% for field in form%}
          <div>
            {{ field.errors }}
            {{ field.label_tag }} {{ field }}
          </div>
        {%endfor%}

        <input type="submit" value="Send e-mail">
        </form>

      
    {%endif%}
{%endblock%}

blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{page.previous_page_number }}">Previous</a>
        {% endif %}
      <span class="current">
         Page {{ page.number }} of {{ page.paginator.num_pages }}.
      </span>
      {% if page.has_next %}
         <a href="?page={{ page.next_page_number }}">Next</a>
       {% endif %}
    </span>
</div>

             